### ISSUE TITLE
Activer support multilangue

### ISSUE THREAD

**Issue by oliche** [oliche/jwaclassic#2]
Et probablement mettre la langue par défaut en anglais ?

**Comment by oliche** [comment]
@JOELWINTER @acrouviere 
La langue par défaut est le français.
Si le site est en anglais, et qu'un post/page n'est pas traduit, la version française s'affiche.

## Installation
Sous linux, il faut aller dans le répertoire du site et taper:
`bundle install`

## Utilisation

### Nom de fichiers
Chaque post/page et son alias doivent s'appeler 
`2018-12-29-Le_Modele_Delahaye_135-en.md`
`2018-12-29-Le_Modele_Delahaye_135-fr.md`
Ou les 2 derniers charactères correspondent à la langue

### Contenu du cartouche
Le cartouche doit contenir les flags `lang` et `permalink`
```
lang: en
permalink: 2018-12-29-Le_Modele_Delahaye_135
```
**Le permalink est le même pour les 2 articles correspondant aux 2 traductions**, sinon ça ne marchera pas.

**Comment by oliche** [comment]
@acrouviere il faudrait mettre à jour les cartouches des posts existants et s'assurer qu'ils sont corrects dans les nouveaux posts.

**Comment by acrouviere** [comment]
vu,
je suis dessus justement

Le jeu. 17 janv. 2019 à 13:54, Olivier Winter <notifications@github.com> a
écrit :

**Comment by acrouviere** [comment]
Could not find gem 'jekyll-polyglot' in any of the gem sources listed in
your Gemfile.

Ca, c'est ce que j'ai dans ubuntu une fois que j'ai fait bundle install


Le jeu. 17 janv. 2019 à 13:54, Olivier Winter <notifications@github.com> a
écrit :

**Comment by oliche** [comment]
Es-tu sur la dernière version ?
`git pull`
`bundle install`

Normalement ton fichier Gemfile doit être identique à celui-là:
https://github.com/oliche/jwaclassic/blob/develop/Gemfile

**Comment by acrouviere** [comment]
Coucou,

mon fichier Gemfile est exactement identique à celui que tu m'as envoyé.
J'ai pourtant toujours les messages d'erreur, et je n'arrive plus à générer
le site en local :(

[image: image.png]

Le jeu. 17 janv. 2019 à 16:33, Olivier Winter <notifications@github.com> a
écrit :

**Comment by oliche** [comment]
mmh, tu es bien dans le répertoire jwaclassic on est d'accord ?
Tu peux essayer :
`rm Gemfile.lock`
` bundle install`

**Comment by acrouviere** [comment]
Demain matin, promis

Le ven. 18 janv. 2019 à 00:07, Olivier Winter <notifications@github.com> a
écrit :

**Comment by acrouviere** [comment]
[image: image.png]

**Comment by acrouviere** [comment]
Et pourtant, sur mon C:/, il y a bien un gemfile et un Gemfile.lock dans
jwaclassic

[image: image.png]
